module RegionHelper
  COUNTY_REGION_MAPPINGS = {
    Aberdeenshire: "Scotland",
    Angus: "Scotland",
    "Argyll and Bute": "Scotland",
    Bedfordshire: "East of England",
    Berkshire: "South East",
    Bristol: "South West",
    Buckinghamshire: "South East",
    Cambridgeshire: "East of England",
    Cheshire: "North West",
    "City of Aberdeen": "Scotland",
    "City of Dundee": "Scotland",
    "City of Edinburgh": "Scotland",
    "City of Glasgow": "Scotland",
    Clackmannanshire: "Scotland",
    Clwyd: "Wales",
    Cornwall: "South West",
    "County Antrim": "Northern Ireland",
    "County Armagh": "Northern Ireland",
    "County Down": "Northern Ireland",
    "County Durham": "North East",
    "County Fermanagh": "Northern Ireland",
    "County Londonderry": "Northern Ireland",
    "County Tyrone": "Northern Ireland",
    Cumbria: "North West",
    Derbyshire: "East Midlands",
    Devon: "South West",
    Dorset: "South West",
    "Dumfries and Galloway": "Scotland",
    Dyfed: "Wales",
    "East Ayrshire": "Scotland",
    "East Dunbartonshire": "Scotland",
    "East Lothian": "Scotland",
    "East Renfrewshire": "Scotland",
    "East Riding of Yorkshire": "Yorkshire & The Humber",
    "East Sussex": "South East",
    Essex: "East of England",
    Falkirk: "Scotland",
    Fife: "Scotland",
    Gloucestershire: "South West",
    "Greater London": "Greater London",
    Gwynedd: "Wales",
    Hampshire: "South East",
    Herefordshire: "West Midlands",
    Hertfordshire: "East of England",
    Highland: "Scotland",
    Inverclyde: "Scotland",
    "Isle of Wight": "South East",
    "Isles of Scilly": "South West",
    Kent: "South East",
    Lancashire: "North West",
    Leicestershire: "East Midlands",
    "Lincolnshire - East Midlands region (includes Boston, East Lindsey, Lincoln, North Kesteven, South Holland, South Kesteven, West Lindsey)": "East Midlands",
    "Lincolnshire - Yorkshire & The Humber region (includes North East Lincolnshire, North Lincolnshire)": "Yorkshire & The Humber",
    Manchester: "North West",
    Merseyside: "North West",
    "Mid Glamorgan": "Wales",
    Midlothian: "Scotland",
    "Gwent - Blaenau Gwent, Caerphilly, Monmouthshire, Newport, Torfaen": "Wales",
    Moray: "Scotland",
    "Na h-Eileanan Siar - Western Isles": "Scotland",
    Norfolk: "East of England",
    "North Ayrshire": "Scotland",
    "North Lanarkshire": "Scotland",
    "North Yorkshire - Yorkshire & The Humber region (includes Craven, Hambleton, Harrogate, Richmondshire, Ryedale, Scarborough, Selby, York)": "Yorkshire & The Humber",
    "North Yorkshire - North East England region (includes Middlesbrough, Redcar and Cleveland, Stockton-on-Tees)": "North East",
    Northamptonshire: "East Midlands",
    Northumberland: "North East",
    Nottinghamshire: "East Midlands",
    "Orkney Islands": "Scotland",
    Oxfordshire: "South East",
    "Perth and Kinross": "Scotland",
    Powys: "Wales",
    Renfrewshire: "Scotland",
    Rutland: "East Midlands",
    "Scottish Borders": "Scotland",
    "Shetland Islands": "Scotland",
    Shropshire: "West Midlands",
    Somerset: "South West",
    "South Ayrshire": "Scotland",
    "South Glamorgan": "Wales",
    "South Lanarkshire": "Scotland",
    "South Yorkshire": "Yorkshire & The Humber",
    Staffordshire: "West Midlands",
    Stirling: "Scotland",
    Suffolk: "East of England",
    Surrey: "South East",
    "Tyne and Wear": "North East",
    Warwickshire: "West Midlands",
    "West Dunbartonshire": "Scotland",
    "West Glamorgan": "Wales",
    "West Lothian": "Scotland",
    "West Midlands": "West Midlands",
    "West Sussex": "South East",
    "West Yorkshire": "Yorkshire & The Humber",
    Wiltshire: "South West",
    Worcestershire: "West Midlands",
    "Bailiwick of Guernsey": "Channel Islands",
    "Bailiwick of Jersey": "Channel Islands",
    "Isle of Man": "Isle of Man",
  }

  PALACE_INVITE_COUNTIES = [
    "Avon",
    "Bath and North East Somerset",
    "Bedford",
    "Bedfordshire",
    "Berkshire",
    "Blackburn with Darwen",
    "Blackpool",
    "Bournemouth",
    "Bournemouth, Christchurch and Poole",
    "Brighton and Hove",
    "Bristol",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cambridgeshire and Isle of Ely",
    "Central Bedfordshire",
    "Cheshire",
    "Cheshire East",
    "Cheshire West and Chester",
    "City of London",
    "Cleveland",
    "Cornwall",
    "County Durham",
    "Cumberland",
    "Cumbria",
    "Darlington",
    "Derby",
    "Derbyshire",
    "Devon",
    "Dorset",
    "East Suffolk",
    "East Sussex",
    "Essex",
    "Gloucestershire",
    "Greater London",
    "Greater Manchester",
    "Halton",
    "Hampshire",
    "Hartlepool",
    "Hereford and Worcester",
    "Herefordshire",
    "Hertfordshire",
    "Humberside",
    "Huntingdon and Peterborough",
    "Huntingdonshire",
    "Isle of Ely",
    "Isle of Wight",
    "Kent",
    "Kingston upon Hull",
    "Lancashire",
    "Leicester",
    "Leicestershire",
    "Lincolnshire",
    "London",
    "Luton",
    "Medway",
    "Merseyside",
    "Middlesbrough",
    "Middlesex",
    "Milton Keynes",
    "Norfolk",
    "North East Lincolnshire",
    "North Humberside",
    "North Lincolnshire",
    "North Northamptonshire",
    "North Somerset",
    "North Yorkshire",
    "Northamptonshire",
    "Northumberland",
    "Nottingham",
    "Nottinghamshire",
    "Oxfordshire",
    "Peterborough",
    "Plymouth",
    "Poole",
    "Portsmouth",
    "Redcar and Cleveland",
    "Rutland",
    "Shropshire",
    "Soke of Peterborough",
    "Somerset",
    "South Gloucestershire",
    "South Humberside",
    "South Yorkshire",
    "Southampton",
    "Southend-on-Sea",
    "Staffordshire",
    "Stockton-on-Tees",
    "Stoke-on-Trent",
    "Suffolk",
    "Surrey",
    "Sussex",
    "Swindon",
    "Telford and Wrekin",
    "Thurrock",
    "Torbay",
    "Tyne and Wear",
    "Warrington",
    "Warwickshire",
    "West Midlands",
    "West Northamptonshire",
    "West Suffolk",
    "West Sussex",
    "West Yorkshire",
    "Westmorland",
    "Wiltshire",
    "Worcestershire",
    "York",
    "Yorkshire",
    "Yorkshire, East Riding",
    "Yorkshire, North Riding",
    "Yorkshire, West Riding",
    "Antrim",
    "Armagh",
    "City of Belfast",
    "City of Derry",
    "Down",
    "Fermanagh",
    "Londonderry",
    "Tyrone",
    "Aberdeenshire",
    "Angus",
    "Argyll",
    "Ayrshire",
    "Banffshire",
    "Berwickshire",
    "Bute",
    "Caithness",
    "City of Aberdeen",
    "City of Dundee",
    "City of Edinburgh",
    "City of Glasgow",
    "Clackmannanshire",
    "Cromartyshire",
    "Dumfriesshire",
    "Dunbartonshire",
    "East Lothian",
    "Fife",
    "Inverness-shire",
    "Kincardineshire",
    "Kinross-shire",
    "Kirkcudbrightshire",
    "Lanarkshire",
    "Midlothian",
    "Moray",
    "Nairnshire",
    "Orkney",
    "Peeblesshire",
    "Perthshire",
    "Renfrewshire",
    "Ross and Cromarty",
    "Ross-shire",
    "Roxburghshire",
    "Selkirkshire",
    "Shetland",
    "Stirlingshire",
    "Sutherland",
    "West Lothian",
    "Wigtownshire",
    "Anglesey",
    "Brecknockshire",
    "Caernarfonshire",
    "Cardiganshire",
    "Carmarthenshire",
    "Clwyd",
    "Denbighshire",
    "Dyfed",
    "Flintshire",
    "Glamorgan",
    "Gwent",
    "Gwynedd",
    "Merionethshire",
    "Mid Glamorgan",
    "Monmouthshire",
    "Montgomeryshire",
    "Pembrokeshire",
    "Powys",
    "Radnorshire",
    "South Glamorgan",
    "West Glamorgan",
    "Wrexham",
  ].freeze

  def counties
    COUNTY_REGION_MAPPINGS.keys.sort
  end

  def palace_invite_counties
    PALACE_INVITE_COUNTIES
  end

  def regions
    COUNTY_REGION_MAPPINGS.values.uniq.sort
  end

  def lookup_region_for_county(county)
    COUNTY_REGION_MAPPINGS[county]
  end
end
